# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eng", models.CharField(max_length=50)),
                ("kor", models.CharField(max_length=50)),
            ],
        ),
    ]
