# Generated by Django 4.1.1 on 2022-09-17 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voca",
            name="today",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
