# Generated by Django 4.1.1 on 2022-10-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_users_delete_example_vocabulary_vocabulary_example_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary_example_deleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Users_delete_example",),
    ]
