# Generated by Django 4.1.1 on 2022-10-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_vocabulary_example_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocas_example",
            name="vocabulary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="study.vocabulary_example",
            ),
        ),
    ]
